/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './index.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'surface-dim': '#dcd9d9',
        'on-background': '#1b1c1c',
        'on-secondary-container': '#fffbff',
        tertiary: '#271f2a',
        'on-secondary': '#ffffff',
        'surface-tint': '#7345b6',
        'on-surface': '#1b1c1c',
        'outline-variant': '#cdc3d4',
        'surface-container': '#f0eded',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        'on-primary-container': '#b889ff',
        'inverse-primary': '#d7baff',
        'tertiary-fixed-dim': '#cfc2d2',
        surface: '#fcf9f8',
        'on-error': '#ffffff',
        'surface-variant': '#e5e2e1',
        outline: '#7c7483',
        'primary-container': '#4a148c',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'tertiary-container': '#3d3440',
        secondary: '#b80049',
        'surface-container-high': '#eae7e7',
        'on-secondary-fixed-variant': '#900038',
        background: '#fcf9f8',
        'surface-container-low': '#f6f3f2',
        'inverse-surface': '#303030',
        'secondary-fixed': '#ffd9de',
        'secondary-container': '#e2165f',
        'on-error-container': '#93000a',
        'primary-fixed': '#eddcff',
        'on-secondary-fixed': '#400014',
        'tertiary-fixed': '#ecdeee',
        'surface-bright': '#fcf9f8',
        'on-primary-fixed': '#280056',
        'on-tertiary-fixed': '#201924',
        primary: '#310065',
        'on-surface-variant': '#4a4452',
        'on-tertiary-container': '#a89cab',
        'on-primary-fixed-variant': '#5a2a9c',
        'primary-fixed-dim': '#d7baff',
        'on-tertiary-fixed-variant': '#4d4450',
        'surface-container-highest': '#e5e2e1',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#ffb2be',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        'container-margin': '20px',
        xs: '4px',
        xl: '48px',
        gutter: '12px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'label-bold': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'display-sos': ['Inter'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'display-sos': ['48px', { lineHeight: '56px', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
